### ISSUE TITLE
可以请大大加一个匹配刚进去的自动要位置功能吗

### ISSUE THREAD

**Issue by miaomiao-222438** [Seraph1ne/LOLAutomationTools#16]
有时候玩匹配，还得打字要位置，如果有个自动打字要位置的功能就好了。许愿🙏

**Comment by Seraph1ne** [comment]
详细描述一下，其实这个功能老早以前就有想过添加进去了，不过后面想了想好像作用不是很大。
你是想让某个英雄选完就发送某个指定的文本，还是只要一进BP界面就发送某个指定文本？

**Comment by miaomiao-222438** [comment]
只要一进BP界面就发送某个指定文本。可以是给英雄加备注的形式。

这个功能主要有两个使用场景
1.比如选了德莱文，想要个硬辅，可以在右键这里多加一行自定义备注，进入bp界面直接秒选英雄+发送备注：“来个硬辅，乱杀”
![image](https://github.com/user-attachments/assets/45e284e8-1ba0-4715-af9d-018fa80d059d)
2.匹配的时候，有时候选个可以摇摆的英雄，队友通常都不知道你走哪路。或者想玩黑科技，队友会对你产生疑问。
比如匹配想玩中单卡尔玛，进入bp界面直接发送提前预设好的备注：“中单卡尔玛”
![image](https://github.com/user-attachments/assets/55ac0c45-3136-4440-b05a-a143d9a27b2f)

**Comment by Seraph1ne** [comment]
![QQ_1735299805973](https://github.com/user-attachments/assets/5c858c7e-d247-46b3-bec6-13b9b443f687)
已上传预览版，功能新增至英雄选用配置页面中了。

**Comment by miaomiao-222438** [comment]
已经用到了谢谢🙏，可以在这个界面加一个英雄搜索功能吗，英雄太多不好找
![Snipaste_2025-01-04_11-37-23](https://github.com/user-attachments/assets/f3ca37f9-0071-42e9-a184-0bfab4e3a843)
